name: Vue 3 CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v4

      - name: 🔧 Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: 📦 Install dependencies
        run: npm ci

      - name: ✅ TypeScript check & Build
        run: npm run build

      - name: 🧹 Lint check
        run: npm run lint

      - name: 💅 Prettier format check
        run: npx prettier --check "src/**/*.{js,ts,vue,json,css,scss,md}"
